# Generated by Django 5.2.6 on 2025-09-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0009_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Select at least 3 skills.', null=True, to='jamapp.skill'),
        ),
    ]
