# Generated by Django 5.2.6 on 2025-09-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0010_skill_jobs_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamapp.jobs'),
        ),
    ]
