# Generated by Django 5.2.6 on 2025-09-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0011_appliedjobs_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
