# Generated by Django 5.2.6 on 2025-09-15 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0012_jobseeker_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(max_length=50)),
                ('interview_details', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField()),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='jamapp.jobseeker')),
            ],
        ),
    ]
