# Generated by Django 5.2.6 on 2025-09-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0013_interviewresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='overall_score',
            field=models.FloatField(blank=True, help_text='Overall score from 0.0 to 1.0', null=True),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Analysis'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Incomplete', 'Incomplete')], default='Pending', max_length=20),
        ),
    ]
