from django.urls import path
from . import views

urlpatterns=[
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('jobseekerreg/', views.jobseekerreg, name='jobseekerreg'),
    path('employerreg/', views.employerreg, name='employerreg'),
    path('login/', views.login, name='login'),
    path('contact/', views.contact, name='contact'),
    path('jsreg/', views.jsreg, name='jsreg'),
    path('ereg/', views.ereg, name='ereg'),
    path('saveenq/', views.saveenq, name='saveenq'),
    path('validate/', views.validate, name='validate'),
    path('emphome/', views.emphome, name='emphome'),
    path('postjob/', views.postjob, name='postjob'),
    path('manageapp/', views.manageapp, name='manageapp'),
    path('empchangepassword/', views.empchangepassword, name='empchangepassword'),
    path('emplogout/', views.emplogout, name='emplogout'),
    path('pjob/', views.pjob, name='pjob'),
    path('empchangepwd/', views.empchangepwd, name='empchangepwd'),
    path('jobhome/', views.jobhome, name='jobhome'),
    path('applyjob/', views.applyjob, name='applyjob'),
    path('jobchangepassword/', views.jobchangepassword, name='jobchangepassword'),
    path('joblogout/', views.joblogout, name='joblogout'),
    path('jobchangepwd/', views.jobchangepwd, name='jobchangepwd'),
    path('myresume/', views.my_resume, name='myresume'),
    path('skill-suggestions/', views.skill_suggestions, name='skill_suggestions'),
    path('appliedjobs/<int:id>/', views.appliedjobs, name='appliedjobs'),
    path('appliedjobsview/', views.appliedjobsview, name='appliedjobsview'),
    path('jsprofile/<int:id>/', views.jsprofile, name='jsprofile'),
    path('adminhome/', views.adminhome, name='adminhome'),
    path('enquiries/', views.enquiries, name='enquiries'),
    path('jobseekers/', views.jobseekers, name='jobseekers'),
    path('employers/', views.employers, name='employers'),
    path('adminlogout/', views.adminlogout, name='adminlogout'),
    path('addnews/', views.addnews, name='addnews'),
    path('deletenews/<int:id>/', views.deletenews, name='deletenews'),
    path('addskills/', views.addSkills, name='addskills'),
    # Mock Interview URLs
    path('mock_interview/', views.mock_interview_options, name='mock_interview_options'),
    path('mock_interview/by_job/', views.mock_interview_job, name='mock_interview_job'),
    path('mock_interview/by_skills/', views.mock_interview_skills, name='mock_interview_skills'),
    path('interview/question/<int:question_number>/', views.interview_session, name='interview_session'),
    path('transcribe/', views.transcribe_audio, name='transcribe_audio'),
    path('interview/terminate/', views.terminate_interview, name='terminate_interview'),
    # Interview Results URLs
    path('interview/history/', views.interview_history, name='interview_history'),
    path('interview/result/<int:result_id>/', views.interview_result_detail, name='interview_result_detail'),
    path('interviewdashboard/', views.interview_dashboard, name='interview_dashboard'),
    path('view_resume/<int:id>/', views.view_resume, name='view_resume'),
    path('career_advice/',views.career_advice,name='career_advice')
]